#!/bin/sh

blocked=0

while read local_ref local_sha remote_ref remote_sha
do
  if [ "$remote_ref" = "refs/heads/master" ]; then
    echo "Pushing to 'master' is blocked in this repo. Push 'development' instead." >&2
    blocked=1
  fi
done

exit $blocked
